name: ANMI
description: Prototype ANMI - Asistente Nutricional Materno Infantil
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.2.2
  shared_preferences: ^2.5.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons: 
    android: true
    ios: true
    image_path: "assets/imgs/AnmiLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/data/
    - .env
    - shorebird.yaml